[package]
name = "aoc"
version = "0.1.0"
authors = ["Christian Persson <saser@live.se>"]

[dependencies]
clap = { version = "2.19.2", features = ["yaml"] }

base = { path = "../base" }

day01 = { path = "../day01" }
day02 = { path = "../day02" }
